### ISSUE TITLE
Stop and re-start the model with infiltration module not possible

### ISSUE THREAD

**Issue by jennykupzig** [SynxFlow/SynxFlow#24]
For an inundation model, used in nowcasting, it is necessary to stop and start the model, saving and loading all required states like water level, flow velocity and soil moisture. 

This start-stop-mechanism works when the infilitation module is neglected and the waterlevel and the flow velocities are set as initial states. However, when the infilitration module is used, there is no  model output created for the soil moisture at the end of the simulation. However, this information is needed to stop and re-start the model when using the infiltration module.

**Example to set initial conditions:**

```
object_to_simulate = hipims_io.InputHipims(case_folder=sim_folder, dem_data=dem)
object_to_simulate.set_initial_condition("h0": np.loadtxt(f"h_{last_timestamp}.asc", skiprows=6))
object_to_simulate.set_initial_condition("hU0x": np.loadtxt(f"hUx_{last_timestamp}.asc", skiprows=6))
object_to_simulate.set_initial_condition("hU0y": np.loadtxt(f"hUy_{last_timestamp}.asc", skiprows=6))
```

_The same should work using `set_grid_parameter` when using the synxflow package (at the moment hipims_io and synxflow are creating both valid folder structures for synxflow. As hipims_io is compatible with hydro_raster package it is more powerful to prepare the dem input data, so it was used in this example)._

**Comment by xiaxilin** [comment]
Adding this would increase the output folder size. Given this is not a frequently used function, I suggest you to implement it by yourself. You can add a new line after Line 363 and Line 665 at 'synxflow/apps/cudaFloodSolversPybind/cuda_flood_solvers.cu'

```python
raster_writer.write(culmulative_depth, "culmulative_depth", _t_out, output_directory.c_str());
```

Then install the package from source code, it will recompile.

synxflow itself should also be compatible with hydro_raster?
