### ISSUE TITLE
pandas.concat 

### ISSUE THREAD

**Issue by zhangrf21** [SynxFlow/SynxFlow#25]
当我运行计算时，会出现以下警告：

D:\ProgramData\Python310\lib\site-packages\synxflow\IO\Boundary.py:246: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_table = data_table.append({'type':'fall', 'extent':None,

怎么使用 "pandas.concat" 改写 Boundary.py 中的 "data_table = data_table.append({'type':'fall', 'extent':None," 呢？

**Comment by xiaxilin** [comment]
This is a warning that isn't currently causing any issue. Please see the documentation of Pandas about changing append into concat.
